apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-app
  labels:
    app: account-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service-app
  template:
    metadata:
      labels:
        app: account-service-app
    spec:
      containers:
        - name: account-service-app
          image: jordidiaz495/account-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: PROFILE
              value: prod
            - name: EUREKA_DEFAULT_ZONE
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_default_zone
            - name: CONFIG_SERVER_SVC
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: config_server_svc